### ISSUE TITLE
Transaction fails

### ISSUE THREAD

**Issue by zolotokrylin** [LayerZero-Labs/LayerZero#17]

**Comment by irondsd** [comment]
`estimateSendFee` function fails. 
Parameters:

```ts
const { nativeFee } = await bridgeContract.estimateSendFee(
  dstChainId, // 1 
  toAddress,
  parsedAmount,
  useZro, // false
  adapterParams // '0x'
)
```
results in error `Error: missing revert data in call exception; Transaction reverted without a reason string`

**Comment by poegva** [comment]
I suppose I understood that the issue can be - new chain IDs should be used in estimate as well

**Comment by irondsd** [comment]
It was fixed and working now. This issue can be closed
